package io.konad.applicative.builders

import io.konad.Maybe.Companion.maybe
import io.konad.curry
import io.konad.hkt.ApplicativeFunctorKind
import io.konad.hkt.FunctorKind

infix fun <F, T, R> ((T) -> R).on(f: FunctorKind<F, T>): FunctorKind<F, R> = f.mapK(this)
infix fun <F, T, R> ((T) -> R).on(f: ApplicativeFunctorKind<F, T>): ApplicativeFunctorKind<F, R> = f.apMapK(this)
infix fun <F, T, R> FunctorKind<F, ((T) -> R)>.on(f: ApplicativeFunctorKind<F, T>): ApplicativeFunctorKind<F, R> = f.apK(this)
infix fun <F, T, R> FunctorKind<F, ((T) -> R)>.on(t: T): FunctorKind<F, R> = mapK { it(t) }
infix fun <T, R> ((T) -> R).on(t: T): R = this(t)

infix operator fun <FU, A, B, RESULT> ((A, B) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, RESULT> ((A, B, C) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, RESULT> ((A, B, C, D) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, RESULT> ((A, B, C, D, E) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, RESULT> ((A, B, C, D, E, F) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, RESULT> ((A, B, C, D, E, F, G) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, RESULT> ((A, B, C, D, E, F, G, H) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, RESULT> ((A, B, C, D, E, F, G, H, I) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J,RESULT> ((A, B, C, D, E, F, G, H, I, J) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, RESULT> ((A, B, C, D, E, F, G, H, I, J, K) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)
infix operator fun <FU, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W) -> RESULT).plus(a: FunctorKind<FU, A>) = curry().on(a)

infix operator fun <A, B, RESULT> ((A, B) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, RESULT> ((A, B, C) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, RESULT> ((A, B, C, D) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, RESULT> ((A, B, C, D, E) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, RESULT> ((A, B, C, D, E, F) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, RESULT> ((A, B, C, D, E, F, G) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, RESULT> ((A, B, C, D, E, F, G, H) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, RESULT> ((A, B, C, D, E, F, G, H, I) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J,RESULT> ((A, B, C, D, E, F, G, H, I, J) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, RESULT> ((A, B, C, D, E, F, G, H, I, J, K) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) -> RESULT).plus(a: A) = curry().on(a)
infix operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, RESULT> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W) -> RESULT).plus(a: A) = curry().on(a)
